on: [push]

jobs:
  install-chainweb:
    runs-on: ubuntu-latest
    name: Test install-chainweb-action
    steps:
    - name: Install latest chainweb-node version
      uses: larskuhtz/install-chainweb-action@master
      with:
        ghc_version: '8.8.3'
        version: '2.1'
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Print chainweb-node version
      run: chainweb-node --version
